### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by urigoren** [pyos/dogeweb#2]
If I understand correctly, I would expect the output of

`list $ map (+9) (1..3)`

to be: `[10,11]`

(Same as `list(map(lambda x:x+9,range(1,3)))` in python 3)

Where in fact, I get a type error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/site-packages/dg/repl.dg", line 105, in runrepl
>     module._ = eval x module.__dict__
>   File "<input>", line 1, in
> TypeError: 'int' object is not callable

Any idea why ?

**Comment by pyos** [comment]
`+9` is "positive 9", you want `+ 9`.

(Also, wrong repository.)
